export const FirstRuContent = {
  title: 'И Д Е А Л',
  desc: [
    `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reiciendis voluptatibus aut quasi ducimus, et mollitia, molestiae excepturi fugit eum velit ex quis delectus dolorum consectetur illum, facilis ad debitis expedita? Porro ratione laudantium quod provident libero sit corrupti eligendi odit culpa accusamus voluptatibus facilis, nisi ducimus blanditiis nesciunt! Alias, quisquam.`,
    `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque blanditiis laborum modi maiores fugiat sapiente facere, qui non dolor odit libero itaque quos ipsa dolore quo ducimus incidunt, numquam officiis. Beatae aut possimus itaque quod nesciunt aliquid reprehenderit, eveniet optio perspiciatis officia eaque esse voluptatem accusamus nulla, deleniti aperiam quo amet sequi voluptatum. Minima sit doloribus neque velit ipsum omnis. Ad corporis dolor, eius quo est rerum quibusdam, illum eaque minima obcaecati atque vitae asperiores!`,
    `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet architecto consequuntur quo iusto cumque vitae veniam sapiente, veritatis, voluptatibus molestias laborum reiciendis cupiditate, itaque ea ducimus impedit harum exercitationem temporibus porro? Suscipit sed praesentium nemo consequuntur ex itaque explicabo id odit, optio adipisci magni vero dignissimos exercitationem incidunt temporibus. Illo, vitae odit deserunt aperiam earum illum temporibus? Aperiam excepturi saepe nisi ab commodi ullam! Eum, asperiores quae? Suscipit natus saepe quam blanditiis hic minus veniam, provident, eveniet adipisci recusandae sed magnam a eum perspiciatis doloribus voluptates ipsam tempore ab, sunt atque laboriosam. Quaerat facere earum enim distinctio eos tempore beatae nesciunt ad alias quae! Quia sed, sunt quaerat eos assumenda quod quidem placeat veritatis porro! Quam doloremque porro provident iure unde laborum illum voluptatibus possimus pariatur rerum, labore, vitae nobis delectus rem vero consectetur, voluptas quo saepe? Omnis at possimus, deserunt laudantium, explicabo impedit quia dignissimos, ad unde sunt obcaecati?`,
  ],
  info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore reiciendis sequi maxime temporibus non fuga dignissimos assumenda, dolorem quas sapiente consectetur cum accusamus deleniti saepe. Aperiam sint dolore earum excepturi odio expedita optio repellat nulla aspernatur voluptatum debitis nemo consequatur unde vel sapiente fuga exercitationem, dicta dolor! Maxime, architecto voluptatibus.',
};
